app = "com-stepbrobd"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  strategy = "rolling"
  max-per-region = 1

[env]
  PORT = "3000"

[experimental]
  allowed_public_ports = [80, 443]
  auto_rollback = false

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    protocol = "http"
    method = "get"
    path = "/"
    interval = "15s"
    grace_period = "300s"
    timeout = "1s"
    restart_limit = 0
