// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[href].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/_app.tsx";
import * as $4 from "./routes/_middleware.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/robots.txt.ts";
import * as $7 from "./routes/sitemap.xml.ts";
import * as $$0 from "./islands/menu.tsx";
import * as $$1 from "./islands/theme.tsx";

const manifest = {
  routes: {
    "./routes/[href].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/_app.tsx": $3,
    "./routes/_middleware.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/robots.txt.ts": $6,
    "./routes/sitemap.xml.ts": $7,
  },
  islands: {
    "./islands/menu.tsx": $$0,
    "./islands/theme.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
